import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Tratata3142',
      email: 'tratata3142@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Tratata',
        logo: '/images/p1.jpg',
        description: 'best seller',
        rating: 4.5,
        numReviews: 89,
      },
    },
    {
      name: 'Boris',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Egor',
      email: 'user1@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Vasya',
      email: 'user2@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'Sanya',
      email: 'user3@gmail.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 0.1,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirts',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirts',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      countInStock: 15,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      countInStock: 6,
      brand: 'Nike',
      rating: 3,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 11,
      brand: 'Adidas',
      rating: 4,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
}

export default data
