const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lacoste Free Shirts',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 220,
      countInStock: 15,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 78,
      countInStock: 6,
      brand: 'Nike',
      rating: 3,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 65,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p1.jpg',
      price: 139,
      countInStock: 11,
      brand: 'Adidas',
      rating: 4,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
}

export default data
